version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.8.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENER_NAME_INTERNAL=INTERNAL://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://kafka:9093,OUTSIDE://localhost:9092

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
      container_name: inventory-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongodb

  order-service:
    build: ./order-service
    dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mongodb

  shipment-service:
    build: ./shipment-service
    dockerfile: Dockerfile
    container_name: shipment-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mongodb

  notification-service:
    build: ./notification-service
    dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  auth-service:
    build:  ./auth-service
    dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - mongo
    networks:
      - microservices-network
